test_raw_cbr_usd_1 = [
    {'NumCode': '008', 'CharCode': 'ALL ', 'Name': 'Албанский лек', 'Convtype': 0, 'Value': '114,3050'},
    {'NumCode': '012', 'CharCode': 'DZD ', 'Name': 'Алжирский динар', 'Convtype': 0,
     'Value': '122,8350'},
    {'NumCode': '973', 'CharCode': 'AOA ', 'Name': 'Ангольская кванза', 'Convtype': 0,
     'Value': '518,3750'},
    {'NumCode': '032', 'CharCode': 'ARS ', 'Name': 'Аргентинское песо', 'Convtype': 0,
     'Value': '63,4635'},
    {'NumCode': '533', 'CharCode': 'AWG ', 'Name': 'Арубанский флорин', 'Convtype': 0,
     'Value': '1,8100'},
    {'NumCode': '971', 'CharCode': 'AFN ', 'Name': 'Афганский афгани', 'Convtype': 0,
     'Value': '75,9500'},
    {'NumCode': '044', 'CharCode': 'BSD ', 'Name': 'Багамский доллар', 'Convtype': 0,
     'Value': '1,0000'},
    {'NumCode': '050', 'CharCode': 'BDT ', 'Name': 'Бангладешская така', 'Convtype': 0,
     'Value': '84,8300'},
    {'NumCode': '052', 'CharCode': 'BBD ', 'Name': 'Барбадосский доллар', 'Convtype': 0,
     'Value': '2,0191'},
    {'NumCode': '048', 'CharCode': 'BHD ', 'Name': 'Бахрейнский динар', 'Convtype': 0,
     'Value': '0,3776'},
    {'NumCode': '084', 'CharCode': 'BZD ', 'Name': 'Белизский доллар', 'Convtype': 0,
     'Value': '2,0157'},
    {'NumCode': '060', 'CharCode': 'BMD ', 'Name': 'Бермудский доллар', 'Convtype': 0,
     'Value': '1,0000'},
    {'NumCode': '068', 'CharCode': 'BOB ', 'Name': 'Боливийский боливиано', 'Convtype': 0,
     'Value': '6,9100'},
    {'NumCode': '072', 'CharCode': 'BWP ', 'Name': 'Ботсванская пула', 'Convtype': 1,
     'Value': '0,0850'},
    {'NumCode': '096', 'CharCode': 'BND ', 'Name': 'Брунейский доллар', 'Convtype': 0,
     'Value': '1,4455'},
    {'NumCode': '108', 'CharCode': 'BIF ', 'Name': 'Бурундийский франк', 'Convtype': 0,
     'Value': '1 888,4400'},
    {'NumCode': '064', 'CharCode': 'BTN ', 'Name': 'Бутанский нгултрум', 'Convtype': 0,
     'Value': '74,9850'},
    {'NumCode': '548', 'CharCode': 'VUV ', 'Name': 'Вануатский вату', 'Convtype': 0,
     'Value': '123,6600'},
    {'NumCode': '928', 'CharCode': 'VES ', 'Name': 'Венесуэльский боливар cоберано', 'Convtype': 0,
     'Value': '72 169,7429'},
    {'NumCode': '951', 'CharCode': 'XCD ', 'Name': 'Восточно - карибский доллар', 'Convtype': 0,
     'Value': '2,7100'},
    {'NumCode': '704', 'CharCode': 'VND ', 'Name': 'Вьетнамский донг', 'Convtype': 0,
     'Value': '23 460,0000'},
    {'NumCode': '332', 'CharCode': 'HTG ', 'Name': 'Гаитский гурд', 'Convtype': 0, 'Value': '95,2635'},
    {'NumCode': '328', 'CharCode': 'GYD ', 'Name': 'Гайанский доллар', 'Convtype': 0,
     'Value': '208,8250'},
    {'NumCode': '270', 'CharCode': 'GMD ', 'Name': 'Гамбийский даласи', 'Convtype': 0,
     'Value': '51,2500'},
    {'NumCode': '936', 'CharCode': 'GHS ', 'Name': 'Ганский седи', 'Convtype': 0, 'Value': '5,5450'},
    {'NumCode': '320', 'CharCode': 'GTQ ', 'Name': 'Гватемальский кетсаль', 'Convtype': 0,
     'Value': '7,6300'},
    {'NumCode': '324', 'CharCode': 'GNF ', 'Name': 'Гвинейский франк', 'Convtype': 0,
     'Value': '9 542,5000'},
    {'NumCode': '292', 'CharCode': 'GIP ', 'Name': 'Гибралтарский фунт', 'Convtype': 1,
     'Value': '1,1712'},
    {'NumCode': '340', 'CharCode': 'HNL ', 'Name': 'Гондурасская лемпира', 'Convtype': 0,
     'Value': '24,7410'},
    {'NumCode': '981', 'CharCode': 'GEL ', 'Name': 'Грузинский лари', 'Convtype': 0, 'Value': '3,0855'},
    {'NumCode': '807', 'CharCode': 'MKD ', 'Name': 'Денар Республики Македония', 'Convtype': 0,
     'Value': '57,2050'},
    {'NumCode': '784', 'CharCode': 'AED ', 'Name': 'Дирхам ОАЭ', 'Convtype': 0, 'Value': '3,6730'},
    {'NumCode': '930', 'CharCode': 'STN ', 'Name': 'Добра Сан-Томе и Принсипи', 'Convtype': 0,
     'Value': '22,8426'},
    {'NumCode': '516', 'CharCode': 'NAD ', 'Name': 'Доллар Намибии', 'Convtype': 0, 'Value': '17,1735'},
    {'NumCode': '090', 'CharCode': 'SBD ', 'Name': 'Доллар Соломоновых Островов', 'Convtype': 1,
     'Value': '0,1206'},
    {'NumCode': '780', 'CharCode': 'TTD ', 'Name': 'Доллар Тринидада и Тобаго', 'Convtype': 0,
     'Value': '6,7567'},
    {'NumCode': '242', 'CharCode': 'FJD ', 'Name': 'Доллар Фиджи', 'Convtype': 1, 'Value': '0,4235'},
    {'NumCode': '214', 'CharCode': 'DOP ', 'Name': 'Доминиканское песо', 'Convtype': 0,
     'Value': '53,7200'},
    {'NumCode': '818', 'CharCode': 'EGP ', 'Name': 'Египетский фунт', 'Convtype': 0,
     'Value': '15,7500'},
    {'NumCode': '967', 'CharCode': 'ZMW ', 'Name': 'Замбийская квача', 'Convtype': 0,
     'Value': '16,9875'},
    {'NumCode': '360', 'CharCode': 'IDR ', 'Name': 'Индонезийская рупия', 'Convtype': 0,
     'Value': '16 172,5150'},
    {'NumCode': '400', 'CharCode': 'JOD ', 'Name': 'Иорданский динар', 'Convtype': 0,
     'Value': '0,7090'}, {'NumCode': '368', 'CharCode': 'IQD ', 'Name': 'Иракский динар', 'Convtype': 0,
                          'Value': '1 193,8100'},
    {'NumCode': '364', 'CharCode': 'IRR ', 'Name': 'Иранский риал', 'Convtype': 0,
     'Value': '42 000,0000'},
    {'NumCode': '352', 'CharCode': 'ISK ', 'Name': 'Исландская крона', 'Convtype': 0,
     'Value': '139,3500'},
    {'NumCode': '886', 'CharCode': 'YER ', 'Name': 'Йеменский риал', 'Convtype': 0,
     'Value': '250,3000'},
    {'NumCode': '116', 'CharCode': 'KHR ', 'Name': 'Камбоджийский риель', 'Convtype': 0,
     'Value': '4 080,0000'},
    {'NumCode': '634', 'CharCode': 'QAR ', 'Name': 'Катарский риал', 'Convtype': 0, 'Value': '3,6410'},
    {'NumCode': '404', 'CharCode': 'KES ', 'Name': 'Кенийский шиллинг', 'Convtype': 0,
     'Value': '105,9000'},
    {'NumCode': '598', 'CharCode': 'PGK ', 'Name': 'Кина Папуа-Новой Гвинеи', 'Convtype': 1,
     'Value': '0,2925'},
    {'NumCode': '170', 'CharCode': 'COP ', 'Name': 'Колумбийское песо', 'Convtype': 0,
     'Value': '4 089,0000'},
    {'NumCode': '174', 'CharCode': 'KMF ', 'Name': 'Коморский франк', 'Convtype': 0,
     'Value': '443,5000'},
    {'NumCode': '977', 'CharCode': 'BAM ', 'Name': 'Конвертируемая марка', 'Convtype': 0,
     'Value': '1,8254'},
    {'NumCode': '976', 'CharCode': 'CDF ', 'Name': 'Конголезский франк', 'Convtype': 0,
     'Value': '1 707,5000'},
    {'NumCode': '188', 'CharCode': 'CRC ', 'Name': 'Костариканский колон', 'Convtype': 0,
     'Value': '565,5000'},
    {'NumCode': '192', 'CharCode': 'CUP ', 'Name': 'Кубинское песо', 'Convtype': 0, 'Value': '1,0000'},
    {'NumCode': '414', 'CharCode': 'KWD ', 'Name': 'Кувейтский динар', 'Convtype': 0,
     'Value': '0,3114'}, {'NumCode': '418', 'CharCode': 'LAK ', 'Name': 'Лаосский кип', 'Convtype': 0,
                          'Value': '8 928,0000'},
    {'NumCode': '430', 'CharCode': 'LRD ', 'Name': 'Либерийский доллар', 'Convtype': 0,
     'Value': '199,5100'},
    {'NumCode': '422', 'CharCode': 'LBP ', 'Name': 'Ливанский фунт', 'Convtype': 0,
     'Value': '1 512,0000'},
    {'NumCode': '434', 'CharCode': 'LYD ', 'Name': 'Ливийский динар', 'Convtype': 0, 'Value': '1,4233'},
    {'NumCode': '480', 'CharCode': 'MUR ', 'Name': 'Маврикийская рупия', 'Convtype': 0,
     'Value': '39,3500'},
    {'NumCode': '929', 'CharCode': 'MRU ', 'Name': 'Мавританская угия', 'Convtype': 0,
     'Value': '37,6000'},
    {'NumCode': '454', 'CharCode': 'MWK ', 'Name': 'Малавийская квача', 'Convtype': 0,
     'Value': '736,5800'},
    {'NumCode': '969', 'CharCode': 'MGA ', 'Name': 'Малагасийский ариари', 'Convtype': 0,
     'Value': '3 765,0000'},
    {'NumCode': '458', 'CharCode': 'MYR ', 'Name': 'Малайзийский ринггит', 'Convtype': 0,
     'Value': '4,3865'},
    {'NumCode': '462', 'CharCode': 'MVR ', 'Name': 'Мальдивская руфия', 'Convtype': 0,
     'Value': '15,4600'},
    {'NumCode': '504', 'CharCode': 'MAD ', 'Name': 'Марокканский дирхам', 'Convtype': 0,
     'Value': '9,7913'},
    {'NumCode': '484', 'CharCode': 'MXN ', 'Name': 'Мексиканское песо', 'Convtype': 0,
     'Value': '23,5190'},
    {'NumCode': '943', 'CharCode': 'MZN ', 'Name': 'Мозамбикский метикал', 'Convtype': 0,
     'Value': '66,3250'},
    {'NumCode': '496', 'CharCode': 'MNT ', 'Name': 'Монгольский тугрик', 'Convtype': 0,
     'Value': '2 775,0000'},
    {'NumCode': '524', 'CharCode': 'NPR ', 'Name': 'Непальская рупия', 'Convtype': 0,
     'Value': '119,9400'},
    {'NumCode': '566', 'CharCode': 'NGN ', 'Name': 'Нигерийская найра', 'Convtype': 0,
     'Value': '306,6500'},
    {'NumCode': '558', 'CharCode': 'NIO ', 'Name': 'Никарагуанская золотая кордоба', 'Convtype': 0,
     'Value': '33,7350'},
    {'NumCode': '554', 'CharCode': 'NZD ', 'Name': 'Новозеландский доллар', 'Convtype': 1,
     'Value': '0,5821'},
    {'NumCode': '376', 'CharCode': 'ILS ', 'Name': 'Новый израильский шекель', 'Convtype': 0,
     'Value': '3,5975'},
    {'NumCode': '901', 'CharCode': 'TWD ', 'Name': 'Новый тайваньский доллар', 'Convtype': 0,
     'Value': '30,2590'},
    {'NumCode': '512', 'CharCode': 'OMR ', 'Name': 'Оманский риал', 'Convtype': 0, 'Value': '0,3850'},
    {'NumCode': '776', 'CharCode': 'TOP ', 'Name': 'Паанга Королевства Тонга', 'Convtype': 1,
     'Value': '0,4344'},
    {'NumCode': '586', 'CharCode': 'PKR ', 'Name': 'Пакистанская рупия', 'Convtype': 0,
     'Value': '159,2000'},
    {'NumCode': '600', 'CharCode': 'PYG ', 'Name': 'Парагвайский гуарани', 'Convtype': 0,
     'Value': '6 643,0000'},
    {'NumCode': '446', 'CharCode': 'MOP ', 'Name': 'Патака Макао', 'Convtype': 0, 'Value': '8,0030'},
    {'NumCode': '604', 'CharCode': 'PEN ', 'Name': 'Перуанский соль', 'Convtype': 0, 'Value': '3,5546'},
    {'NumCode': '222', 'CharCode': 'SVC ', 'Name': 'Сальвадорский колон', 'Convtype': 0,
     'Value': '8,7545'},
    {'NumCode': '682', 'CharCode': 'SAR ', 'Name': 'Саудовский риял', 'Convtype': 0, 'Value': '3,7608'},
    {'NumCode': '748', 'CharCode': 'SZL ', 'Name': 'Свазилендский лилангени', 'Convtype': 0,
     'Value': '17,1735'},
    {'NumCode': '408', 'CharCode': 'KPW ', 'Name': 'Северокорейская вона', 'Convtype': 0,
     'Value': '130,0000'},
    {'NumCode': '690', 'CharCode': 'SCR ', 'Name': 'Сейшельская рупия', 'Convtype': 0,
     'Value': '13,7050'},
    {'NumCode': '941', 'CharCode': 'RSD ', 'Name': 'Сербский динар', 'Convtype': 0,
     'Value': '109,0200'},
    {'NumCode': '760', 'CharCode': 'SYP ', 'Name': 'Сирийский фунт', 'Convtype': 0,
     'Value': '436,5000'},
    {'NumCode': '706', 'CharCode': 'SOS ', 'Name': 'Сомалийский шиллинг', 'Convtype': 0,
     'Value': '578,5000'},
    {'NumCode': '938', 'CharCode': 'SDG ', 'Name': 'Суданский фунт', 'Convtype': 0, 'Value': '55,1277'},
    {'NumCode': '968', 'CharCode': 'SRD ', 'Name': 'Суринамский доллар', 'Convtype': 0,
     'Value': '7,4750'},
    {'NumCode': '694', 'CharCode': 'SLL ', 'Name': 'Сьерра-Леонский леоне', 'Convtype': 0,
     'Value': '9 719,2100'},
    {'NumCode': '764', 'CharCode': 'THB ', 'Name': 'Таиландский бат', 'Convtype': 0,
     'Value': '32,5450'},
    {'NumCode': '834', 'CharCode': 'TZS ', 'Name': 'Танзанийский шиллинг', 'Convtype': 0,
     'Value': '2 306,0000'},
    {'NumCode': '788', 'CharCode': 'TND ', 'Name': 'Тунисский динар', 'Convtype': 0, 'Value': '2,9284'},
    {'NumCode': '800', 'CharCode': 'UGX ', 'Name': 'Угандийский шиллинг', 'Convtype': 0,
     'Value': '3 832,5000'},
    {'NumCode': '858', 'CharCode': 'UYU ', 'Name': 'Уругвайское песо', 'Convtype': 0,
     'Value': '45,9550'},
    {'NumCode': '608', 'CharCode': 'PHP ', 'Name': 'Филиппинское писо', 'Convtype': 0,
     'Value': '51,1100'},
    {'NumCode': '262', 'CharCode': 'DJF ', 'Name': 'Франк Джибути', 'Convtype': 0, 'Value': '178,0250'},
    {'NumCode': '950', 'CharCode': 'XAF ', 'Name': 'Франк КФА ВЕАС', 'Convtype': 0,
     'Value': '611,6200'},
    {'NumCode': '952', 'CharCode': 'XOF ', 'Name': 'Франк КФА ВСЕАО', 'Convtype': 0,
     'Value': '583,7000'},
    {'NumCode': '646', 'CharCode': 'RWF ', 'Name': 'Франк Руанды', 'Convtype': 0, 'Value': '952,0285'},
    {'NumCode': '654', 'CharCode': 'SHP ', 'Name': 'Фунт Св. Елены', 'Convtype': 1, 'Value': '1,1654'},
    {'NumCode': '238', 'CharCode': 'FKP ', 'Name': 'Фунт Фолклендских островов', 'Convtype': 1,
     'Value': '1,1712'},
    {'NumCode': '191', 'CharCode': 'HRK ', 'Name': 'Хорватская куна', 'Convtype': 0, 'Value': '7,0602'},
    {'NumCode': '152', 'CharCode': 'CLP ', 'Name': 'Чилийское песо', 'Convtype': 0,
     'Value': '862,3000'},
    {'NumCode': '144', 'CharCode': 'LKR ', 'Name': 'Шри-Ланкийская рупия', 'Convtype': 0,
     'Value': '187,0500'},
    {'NumCode': '232', 'CharCode': 'ERN ', 'Name': 'Эритрейская накфа', 'Convtype': 0,
     'Value': '15,0750'},
    {'NumCode': '132', 'CharCode': 'CVE ', 'Name': 'Эскудо Кабо-Верде', 'Convtype': 0,
     'Value': '103,0050'},
    {'NumCode': '230', 'CharCode': 'ETB ', 'Name': 'Эфиопский быр', 'Convtype': 0, 'Value': '32,6000'},
    {'NumCode': '388', 'CharCode': 'JMD ', 'Name': 'Ямайский доллар', 'Convtype': 0,
     'Value': '135,5000'}]

test_raw_cbr_usd_2_1conv = [
    {'NumCode': '072', 'CharCode': 'BWP ', 'Name': 'Ботсванская пула', 'Convtype': 1, 'Value': '0,0850'},
    {'NumCode': '292', 'CharCode': 'GIP ', 'Name': 'Гибралтарский фунт', 'Convtype': 1, 'Value': '1,1712'},
    {'NumCode': '090', 'CharCode': 'SBD ', 'Name': 'Доллар Соломоновых Островов', 'Convtype': 1, 'Value': '0,1206'},
    {'NumCode': '242', 'CharCode': 'FJD ', 'Name': 'Доллар Фиджи', 'Convtype': 1, 'Value': '0,4235'},
    {'NumCode': '598', 'CharCode': 'PGK ', 'Name': 'Кина Папуа-Новой Гвинеи', 'Convtype': 1, 'Value': '0,2925'},
    {'NumCode': '554', 'CharCode': 'NZD ', 'Name': 'Новозеландский доллар', 'Convtype': 1, 'Value': '0,5821'},
    {'NumCode': '776', 'CharCode': 'TOP ', 'Name': 'Паанга Королевства Тонга', 'Convtype': 1, 'Value': '0,4344'},
    {'NumCode': '654', 'CharCode': 'SHP ', 'Name': 'Фунт Св. Елены', 'Convtype': 1, 'Value': '1,1654'},
    {'NumCode': '238', 'CharCode': 'FKP ', 'Name': 'Фунт Фолклендских островов', 'Convtype': 1, 'Value': '1,1712'},
]
